<a href="https://colab.research.google.com/github/Abhishek3102/ML/blob/main/Sentiment_Analysis_using_RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import numpy as np

text = ['hello people, how are u all?',
        'tereko kitne baar bolne ka ki lafda mat kar',
        'diwali ke dino me mithai nahi dega to kaisa chalega',
        'please forgive me for my mistakes'
]

In [22]:
!pip install keras

In [23]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token='<oov>')
tokenizer.fit_on_texts(text)

In [24]:
tokenizer.word_index

{'<oov>': 1,
 'me': 2,
 'hello': 3,
 'people': 4,
 'how': 5,
 'are': 6,
 'u': 7,
 'all': 8,
 'tereko': 9,
 'kitne': 10,
 'baar': 11,
 'bolne': 12,
 'ka': 13,
 'ki': 14,
 'lafda': 15,
 'mat': 16,
 'kar': 17,
 'diwali': 18,
 'ke': 19,
 'dino': 20,
 'mithai': 21,
 'nahi': 22,
 'dega': 23,
 'to': 24,
 'kaisa': 25,
 'chalega': 26,
 'please': 27,
 'forgive': 28,
 'for': 29,
 'my': 30,
 'mistakes': 31}

In [25]:
tokenizer.word_counts

OrderedDict([('hello', 1),
             ('people', 1),
             ('how', 1),
             ('are', 1),
             ('u', 1),
             ('all', 1),
             ('tereko', 1),
             ('kitne', 1),
             ('baar', 1),
             ('bolne', 1),
             ('ka', 1),
             ('ki', 1),
             ('lafda', 1),
             ('mat', 1),
             ('kar', 1),
             ('diwali', 1),
             ('ke', 1),
             ('dino', 1),
             ('me', 2),
             ('mithai', 1),
             ('nahi', 1),
             ('dega', 1),
             ('to', 1),
             ('kaisa', 1),
             ('chalega', 1),
             ('please', 1),
             ('forgive', 1),
             ('for', 1),
             ('my', 1),
             ('mistakes', 1)])

In [26]:
print("The number of sentences provided are :",tokenizer.document_count)

The number of sentences provided are : 4


In [27]:
sequences = tokenizer.texts_to_sequences(text)
print(sequences)

[[3, 4, 5, 6, 7, 8], [9, 10, 11, 12, 13, 14, 15, 16, 17], [18, 19, 20, 2, 21, 22, 23, 24, 25, 26], [27, 28, 2, 29, 30, 31]]


In [28]:
from tensorflow.keras.utils import pad_sequences

In [29]:
sequences = pad_sequences(sequences, padding='post')
print(sequences)

[[ 3  4  5  6  7  8  0  0  0  0]
 [ 9 10 11 12 13 14 15 16 17  0]
 [18 19 20  2 21 22 23 24 25 26]
 [27 28  2 29 30 31  0  0  0  0]]


In [30]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [31]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

In [32]:
X_train[0]

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 22665,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 21631,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 19193,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 10311,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 31050,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 12118,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5

In [33]:
len(X_train[2])

141

In [34]:
X_train = pad_sequences(X_train,padding='post')
X_test = pad_sequences(X_test,padding='post')

In [35]:
X_train[0]

array([ 1, 14, 22, ...,  0,  0,  0], dtype=int32)

In [36]:
model = Sequential()

model.add(SimpleRNN(32,input_shape=(50,1),return_sequences=False))
model.add(Dense(1,activation='sigmoid'))

model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ simple_rnn_1 (SimpleRNN)             │ (None, 32)                  │           1,088 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,121 (4.38 KB)

 Trainable params: 1,121 (4.38 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

model.fit(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 387s 491ms/step - accuracy: 0.4993 - loss: 0.6959 - val_accuracy: 0.5000 - val_loss: 0.6936
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 427s 474ms/step - accuracy: 0.4963 - loss: 0.6943 - val_accuracy: 0.4962 - val_loss: 0.6947
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 382s 474ms/step - accuracy: 0.4989 - loss: 0.6939 - val_accuracy: 0.5000 - val_loss: 0.6933
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 372s 476ms/step - accuracy: 0.4998 - loss: 0.6938 - val_accuracy: 0.5032 - val_loss: 0.6934
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 440s 551ms/step - accuracy: 0.4978 - loss: 0.6938 - val_accuracy: 0.5038 - val_loss: 0.6932
